import * as ImgUrl from './officeimgurls'
import * as PlanStatus from './planstatus'

export const rows = [
    {
      id: 1,
      lastName: 'Scott',
      firstName: 'Michael',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Executive',
      avatar: ImgUrl.imgUrlMichael,
      planstatus: PlanStatus.VESTING_STATUS_NO_PLAN,
      statusdesc: PlanStatus.VESTING_STATUS_NO_PLAN_DESC,
    },
    {
      id: 2,
      lastName: 'Schrute',
      firstName: 'Dwight',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Sales',
      avatar: ImgUrl.imgUrlDwight,
      planstatus: PlanStatus.VESTING_STATUS_VESTING,
      statusdesc: PlanStatus.VESTING_STATUS_VESTING_DESC,
    },
    {
      id: 3,
      lastName: 'Halpert',
      firstName: 'Jim',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Sales',
      avatar: ImgUrl.imgUrlJim,
      planstatus: PlanStatus.VESTING_STATUS_NO_PLAN,
      statusdesc: PlanStatus.VESTING_STATUS_NO_PLAN_DESC,
    },
    {
      id: 4,
      lastName: 'Kapoor',
      firstName: 'Kelly',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Operations',
      avatar: ImgUrl.imgUrlKelly,
      planstatus: PlanStatus.VESTING_STATUS_EMP_DEPART,
      statusdesc: PlanStatus.VESTING_STATUS_EMP_DEPART_DESC,
    },
    {
      id: 5,
      lastName: 'Bernard',
      firstName: 'Andy',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Sales',
      avatar: ImgUrl.imgUrlAndy,
      planstatus: PlanStatus.VESTING_STATUS_Benefit_TO_SEND,
      statusdesc: PlanStatus.VESTING_STATUS_Benefit_TO_SEND_DESC,
    },
    {
      id: 6,
      lastName: 'Philbin',
      firstName: 'Darryl',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Operations',
      avatar: ImgUrl.imgUrlDarryl,
      planstatus: PlanStatus.VESTING_STATUS_VESTED,
      statusdesc: PlanStatus.VESTING_STATUS_VESTED_DESC,
    },
    {
      id: 7,
      lastName: 'Beesly',
      firstName: 'Pam',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Operations',
      avatar: ImgUrl.imgUrlPam,
      planstatus: PlanStatus.VESTING_STATUS_IN_DEFAULT,
      statusdesc: PlanStatus.VESTING_STATUS_IN_DEFAULT_DESC,
    },
    {
      id: 8,
      lastName: 'Stanley',
      firstName: 'Hudson',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Sales',
      avatar: ImgUrl.imgUrlStanley,
      planstatus: PlanStatus.VESTING_STATUS_EMP_TO_SIGN,
      statusdesc: PlanStatus.VESTING_STATUS_EMP_TO_SIGN_DESC,
    },
    {
      id: 9,
      lastName: 'Howard',
      firstName: 'Ryan',
      eid: 'E28729',
      uei: 123456789,
      startdate: '01/01/2020',
      dept: 'Sales',
      avatar: ImgUrl.imgUrlRyan,
      planstatus: PlanStatus.VESTING_STATUS_CONTRACT_SIGNED,
      statusdesc: PlanStatus.VESTING_STATUS_CONTRACT_SIGNED_DESC,
    },
  ]
