
export const VESTING_STATUS_VESTING = "VESTING"
export const VESTING_STATUS_VESTING_DESC = "BONUS VESTING"

export const VESTING_STATUS_VESTED = "VESTED"
export const VESTING_STATUS_VESTED_DESC = "BONUS VESTED"

export const VESTING_STATUS_CONTRACT_SIGNED = "SIGNED"
export const VESTING_STATUS_CONTRACT_SIGNED_DESC = "CONTRACT SIGNED, DISBURSING FUNDS"

export const VESTING_STATUS_EMP_DEPART = "DEPARTURE"
export const VESTING_STATUS_EMP_DEPART_DESC = "EMPLOYEE DEPARTURE - MOVING TO LOAN MODEL"

export const VESTING_STATUS_Benefit_TO_SEND = "SENDING"
export const VESTING_STATUS_Benefit_TO_SEND_DESC = "Benefit TO SEND CONTRACT"

export const VESTING_STATUS_IN_DEFAULT = "DEFAULT"
export const VESTING_STATUS_IN_DEFAULT_DESC = "LOAN IN DEFAULT - MOVING TO COLLECTIONS"

export const VESTING_STATUS_EMP_TO_SIGN = "TO SIGN"
export const VESTING_STATUS_EMP_TO_SIGN_DESC = "EMPLOYEE TO SIGN CONTRACT"

export const VESTING_STATUS_NO_PLAN = "NO PLAN"
export const VESTING_STATUS_NO_PLAN_DESC = "EMPLOYEE DOES NOT HAVE A BONUS PLAN"
